version: '3'

services:
  the-pub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./content:/app/content
    restart: unless-stopped