services:
  the-pub:
    container_name: 5e-Pub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:3000"
    environment:
      - NODE_ENV=production
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./content:/app/content
    restart: unless-stopped
